export const polkadotChains = {
  polkadot: {
    display: "Polkadot",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fpolkadot.png&w=96&q=75",
    paraChainId: -1,
    ss58Prefix: 0,
  },
  assetHubPolkadot: {
    display: "Asset Hub Polkadot",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fstatemine.png&w=96&q=75",
    paraChainId: 1000,
    ss58Prefix: 0,
  },
  acala: {
    display: "Acala",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Facala.png&w=96&q=75",
    paraChainId: 2000,
    ss58Prefix: 10,
  },
  parallel: {
    display: "Parallel",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fparallel.png&w=96&q=75",
    paraChainId: 2012,
    ss58Prefix: 172,
  },
  moonbeam: {
    display: "Moonbeam",
    type: "ethereum",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fmoonbeam.png&w=96&q=75",
    paraChainId: 2004,
    ss58Prefix: 1284,
  },
  interlay: {
    display: "Interlay",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Finterlay.png&w=96&q=75",
    paraChainId: 2032,
    ss58Prefix: 2032,
  },
  astar: {
    display: "Astar",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fastar.png&w=96&q=75",
    paraChainId: 2006,
    ss58Prefix: 5,
  },
  hydradx: {
    display: "HydraDX",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fhydra.png&w=96&q=75",
    paraChainId: 2034,
    ss58Prefix: 63,
  },
  zeitgeist: {
    display: "Zeitgeist",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fzeitgeist.png&w=96&q=75",
    paraChainId: 2092,
    ss58Prefix: 73,
  },
  unique: {
    display: "Unique Network",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Funique.png&w=96&q=75",
    paraChainId: 2037,
    ss58Prefix: 7391,
  },
  centrifuge: {
    display: "Centrifuge",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2031,
    ss58Prefix: 36,
  },
  subsocial: {
    id: "subsocial",
    display: "Subsocial",
    type: "substrate",
    icon: "https://sub.id/images/subsocial.svg",
    paraChainId: 2101,
    ss58Prefix: 28,
  },
  bifrostPolkadot: {
    display: "Bifrost",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fbifrost.png&w=96&q=75",
    paraChainId: 2030,
    ss58Prefix: 6,
  },
};
