export const kusamaChains = {
  kusama: {
    id: "kusama",
    display: "Kusama",
    icon: "https://resources.acala.network/networks/kusama.png",
    paraChainId: -1,
    ss58Prefix: 2,
  },
  statemine: {
    id: "statemine",
    display: "Statemine",
    icon: "https://resources.acala.network/networks/statemine.png",
    paraChainId: 2001,
    ss58Prefix: 2,
  },
  karura: {
    id: "karura",
    display: "Karura",
    icon: "https://resources.acala.network/networks/karura.png",
    paraChainId: 2000,
    ss58Prefix: 8,
  },
  quartz: {
    id: "quartz",
    display: "Quartz",
    icon: "https://resources.acala.network/networks/quartz.png",
    paraChainId: 2095,
    ss58Prefix: 255,
  },
  bifrost: {
    id: "bifrost",
    display: "Bifrost",
    icon: "https://resources.acala.network/networks/bifrost.png",
    paraChainId: 2001,
    ss58Prefix: 6,
  },
  khala: {
    id: "khala",
    display: "Khala",
    icon: "https://resources.acala.network/networks/khala.png",
    paraChainId: 2004,
    ss58Prefix: 30,
  },
  kintsugi: {
    id: "kintsugi",
    display: "Kintsugi",
    icon: "https://resources.acala.network/networks/kintsugi.png",
    paraChainId: 2092,
    ss58Prefix: 2092,
  },
};
