
  // This file is generated by scripts/generate-bridge-document.ts
  export default [
  [
    {
      "to": "polkadot",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "19978738"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "GLMR",
      "xcm": {
        "fee": {
          "token": "GLMR",
          "amount": "8000000000000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "24963428577"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "2000000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "447889166"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "45977011"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "ASTR",
      "xcm": {
        "fee": {
          "token": "ASTR",
          "amount": "4006410300000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "1108000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "252800000"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "3692000"
        }
      },
      "from": "acala"
    },
    {
      "to": "interlay",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "20000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "interlay",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "72"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "DAI",
      "xcm": {
        "fee": {
          "token": "DAI",
          "amount": "2926334210356268"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "491129243"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "WETH",
      "xcm": {
        "fee": {
          "token": "WETH",
          "amount": "956965470918"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "WBTC",
      "xcm": {
        "fee": {
          "token": "WBTC",
          "amount": "6"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "11516111"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "10429291793"
        }
      },
      "from": "acala"
    },
    {
      "to": "unique",
      "token": "UNQ",
      "xcm": {
        "fee": {
          "token": "UNQ",
          "amount": ""
        }
      },
      "from": "acala"
    },
    {
      "to": "assetHubPolkadot",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "160000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "assetHubPolkadot",
      "token": "USDC",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "160000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "assetHubPolkadot",
      "token": "PINK",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "160000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "kusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "79999999"
        }
      },
      "from": "karura"
    },
    {
      "to": "assetHubKusama",
      "token": "RMRK",
      "xcm": {
        "fee": {
          "token": "RMRK",
          "amount": "100000"
        }
      },
      "from": "karura"
    },
    {
      "to": "assetHubKusama",
      "token": "ARIS",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "16000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "assetHubKusama",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "1183"
        }
      },
      "from": "karura"
    },
    {
      "to": "shiden",
      "token": "SDN",
      "xcm": {
        "fee": {
          "token": "SDN",
          "amount": "3519949300000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shiden",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "2080000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "BNC",
      "xcm": {
        "fee": {
          "token": "BNC",
          "amount": "5120000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "5120000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "4800000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "25600000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "VSKSM",
      "xcm": {
        "fee": {
          "token": "VSKSM",
          "amount": "64000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "altair",
      "token": "AIR",
      "xcm": {
        "fee": {
          "token": "AIR",
          "amount": "9269600000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "altair",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "51200000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shadow",
      "token": "CSM",
      "xcm": {
        "fee": {
          "token": "CSM",
          "amount": "4000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shadow",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "4000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shadow",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "4000"
        }
      },
      "from": "karura"
    },
    {
      "to": "crab",
      "token": "CRAB",
      "xcm": {
        "fee": {
          "token": "CRAB",
          "amount": "4000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "integritee",
      "token": "TEER",
      "xcm": {
        "fee": {
          "token": "TEER",
          "amount": "4000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "kintsugi",
      "token": "KINT",
      "xcm": {
        "fee": {
          "token": "KINT",
          "amount": "220000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "kintsugi",
      "token": "KBTC",
      "xcm": {
        "fee": {
          "token": "KBTC",
          "amount": "85"
        }
      },
      "from": "karura"
    },
    {
      "to": "kintsugi",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "190000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "khala",
      "token": "PHA",
      "xcm": {
        "fee": {
          "token": "PHA",
          "amount": "64000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "khala",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "16000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "khala",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "8000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "100000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "KMA",
      "xcm": {
        "fee": {
          "token": "KMA",
          "amount": "4000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "100000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "100000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "7692307692"
        }
      },
      "from": "karura"
    },
    {
      "to": "moonriver",
      "token": "MOVR",
      "xcm": {
        "fee": {
          "token": "MOVR",
          "amount": "80000000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "moonriver",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "353666600"
        }
      },
      "from": "karura"
    },
    {
      "to": "moonriver",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "9880000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "moonriver",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "16536000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "TUR",
      "xcm": {
        "fee": {
          "token": "TUR",
          "amount": "1664000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "32000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "256000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "BSX",
      "xcm": {
        "fee": {
          "token": "BSX",
          "amount": "22000000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "359882060"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "3150402683"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "DAI",
      "xcm": {
        "fee": {
          "token": "DAI",
          "amount": "4400000000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "USDCet",
      "xcm": {
        "fee": {
          "token": "USDCet",
          "amount": "4400"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "WETH",
      "xcm": {
        "fee": {
          "token": "WETH",
          "amount": "2926000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "WBTC",
      "xcm": {
        "fee": {
          "token": "WBTC",
          "amount": "22"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "LT",
      "xcm": {
        "fee": {
          "token": "LT",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "quartz",
      "token": "QTZ",
      "xcm": {
        "fee": {
          "token": "QTZ",
          "amount": "0"
        }
      },
      "from": "karura"
    }
  ],
  [
    {
      "to": "polkadot",
      "token": "DOT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "309700000"
        },
        "fee": {
          "token": "DOT",
          "amount": "421500000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "hydradx",
      "token": "USDT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "USDT",
          "amount": "2200"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "acala",
      "token": "USDT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "USDT",
          "amount": "808"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "acala",
      "token": "USDC",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "USDC",
          "amount": "803"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "acala",
      "token": "PINK",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "PINK",
          "amount": "80370000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "astar",
      "token": "USDT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "USDT",
          "amount": "808"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "interlay",
      "token": "USDT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "USDT",
          "amount": "25000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "interlay",
      "token": "USDC",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "USDC",
          "amount": "25000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "moonbeam",
      "token": "USDT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "311100000"
        },
        "fee": {
          "token": "USDT",
          "amount": "808"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubPolkadot"
    },
    {
      "to": "kusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "90049287"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1032333300"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubKusama"
    },
    {
      "to": "karura",
      "token": "RMRK",
      "xcm": {
        "deliveryFee": {
          "token": "KSM",
          "amount": "1036333296"
        },
        "fee": {
          "token": "RMRK",
          "amount": "9918117"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubKusama"
    },
    {
      "to": "karura",
      "token": "ARIS",
      "xcm": {
        "fee": {
          "token": "ARIS",
          "amount": "6400000"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1036333296"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubKusama"
    },
    {
      "to": "karura",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "808"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1036333296"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubKusama"
    },
    {
      "to": "kintsugi",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "20000"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1036333296"
        },
        "weightLimit": "Unlimited"
      },
      "from": "assetHubKusama"
    }
  ],
  [
    {
      "to": "acala",
      "token": "ASTR",
      "xcm": {
        "fee": {
          "token": "ASTR",
          "amount": "8082400000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "acala",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "8082400000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "acala",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "1815098681"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "acala",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "13400229"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "hydradx",
      "token": "ASTR",
      "xcm": {
        "fee": {
          "token": "ASTR",
          "amount": "44306118000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "assetHubPolkadot",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "44306118000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "interlay",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "75"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "interlay",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "20000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "karura",
      "token": "SDN",
      "xcm": {
        "fee": {
          "token": "SDN",
          "amount": "801280000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "shiden"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "2120203588"
        },
        "weightLimit": "Unlimited"
      },
      "from": "shiden"
    }
  ],
  [
    {
      "to": "karura",
      "token": "BNC",
      "xcm": {
        "fee": {
          "token": "BNC",
          "amount": "5120000000"
        }
      },
      "from": "bifrost"
    },
    {
      "to": "karura",
      "token": "VSKSM",
      "xcm": {
        "fee": {
          "token": "VSKSM",
          "amount": "64000000"
        }
      },
      "from": "bifrost"
    },
    {
      "to": "karura",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "64000000"
        }
      },
      "from": "bifrost"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        }
      },
      "from": "bifrost"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "10011896008"
        }
      },
      "from": "bifrost"
    },
    {
      "to": "kintsugi",
      "token": "VKSM",
      "xcm": {
        "fee": {
          "token": "VKSM",
          "amount": "175000000"
        }
      },
      "from": "bifrost"
    }
  ],
  [
    {
      "to": "kusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "104571640"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "BSX",
      "xcm": {
        "fee": {
          "token": "BSX",
          "amount": "93240000000"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "aUSD",
      "xcm": {
        "fee": {
          "token": "aUSD",
          "amount": "5060238106"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "90741527"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "DAI",
      "xcm": {
        "fee": {
          "token": "DAI",
          "amount": "808240000000000"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "USDCet",
      "xcm": {
        "fee": {
          "token": "USDCet",
          "amount": "808"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "WETH",
      "xcm": {
        "fee": {
          "token": "WETH",
          "amount": "449022222222"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "WBTC",
      "xcm": {
        "fee": {
          "token": "WBTC",
          "amount": "2"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "assetHubKusama",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "1183"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "tinkernet",
      "token": "TNKR",
      "xcm": {
        "fee": {
          "token": "TNKR",
          "amount": "9270203240"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "robonomics",
      "token": "XRT",
      "xcm": {
        "fee": {
          "token": "XRT",
          "amount": "4632"
        }
      },
      "from": "basilisk"
    }
  ],
  [
    {
      "to": "karura",
      "token": "TEER",
      "xcm": {
        "fee": {
          "token": "TEER",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "integritee"
    }
  ],
  [
    {
      "to": "acala",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "81000000"
        }
      },
      "from": "interlay"
    },
    {
      "to": "acala",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "9"
        }
      },
      "from": "interlay"
    },
    {
      "to": "astar",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "40000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "interlay"
    },
    {
      "to": "astar",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "5"
        },
        "weightLimit": "5000000000"
      },
      "from": "interlay"
    },
    {
      "to": "phala",
      "token": "PHA",
      "xcm": {
        "fee": {
          "token": "PHA",
          "amount": "65000000000"
        }
      },
      "from": "interlay"
    },
    {
      "to": "phala",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "650000000"
        }
      },
      "from": "interlay"
    },
    {
      "to": "phala",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "6500000"
        }
      },
      "from": "interlay"
    },
    {
      "to": "polkadot",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "1000000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "interlay"
    },
    {
      "to": "assetHubPolkadot",
      "token": "USDC",
      "xcm": {
        "fee": {
          "token": "USDC",
          "amount": "80000"
        },
        "weightLimit": "5000000000"
      },
      "from": "interlay"
    },
    {
      "to": "assetHubPolkadot",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "80000"
        }
      },
      "from": "interlay"
    },
    {
      "to": "hydradx",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "15"
        }
      },
      "from": "interlay"
    },
    {
      "to": "hydradx",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "1500000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "interlay"
    },
    {
      "to": "hydradx",
      "token": "HDX",
      "xcm": {
        "fee": {
          "token": "HDX",
          "amount": "100000000000"
        }
      },
      "from": "interlay"
    },
    {
      "to": "bifrostPolkadot",
      "token": "VDOT",
      "xcm": {
        "fee": {
          "token": "VDOT",
          "amount": "725"
        },
        "weightLimit": "5000000000"
      },
      "from": "interlay"
    },
    {
      "to": "bifrostPolkadot",
      "token": "BNC",
      "xcm": {
        "fee": {
          "token": "BNC",
          "amount": "550000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "interlay"
    },
    {
      "to": "karura",
      "token": "KINT",
      "xcm": {
        "fee": {
          "token": "KINT",
          "amount": "210000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    },
    {
      "to": "karura",
      "token": "KBTC",
      "xcm": {
        "fee": {
          "token": "KBTC",
          "amount": "85"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "270000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    },
    {
      "to": "kusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "100000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    },
    {
      "to": "assetHubKusama",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "10000"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    },
    {
      "to": "bifrost",
      "token": "VKSM",
      "xcm": {
        "fee": {
          "token": "VKSM",
          "amount": "85000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    }
  ],
  [
    {
      "to": "karura",
      "token": "LT",
      "xcm": {
        "fee": {
          "token": "LT",
          "amount": "93240000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "9324000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "5693632140"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "739331668"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    }
  ],
  [
    {
      "to": "karura",
      "token": "KMA",
      "xcm": {
        "fee": {
          "token": "KMA",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "6381112603"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "452334406"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "54632622"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    }
  ],
  [
    {
      "to": "acala",
      "token": "GLMR",
      "xcm": {
        "fee": {
          "token": "GLMR",
          "amount": "1000000000"
        }
      },
      "from": "moonbeam"
    },
    {
      "to": "acala",
      "token": "xcACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "1000000000"
        }
      },
      "from": "moonbeam"
    },
    {
      "to": "acala",
      "token": "xcaUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "1000000000"
        }
      },
      "from": "moonbeam"
    },
    {
      "to": "acala",
      "token": "xcDOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "1000000000"
        }
      },
      "from": "moonbeam"
    }
  ],
  [
    {
      "to": "karura",
      "token": "TUR",
      "xcm": {
        "fee": {
          "token": "TUR",
          "amount": "2560000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "2626579278"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "480597195"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    }
  ],
  [
    {
      "to": "interlay",
      "token": "PHA",
      "xcm": {
        "fee": {
          "token": "PHA",
          "amount": "80000000000000"
        }
      },
      "from": "phala"
    },
    {
      "to": "interlay",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "70"
        }
      },
      "from": "phala"
    },
    {
      "to": "interlay",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "20000000"
        }
      },
      "from": "phala"
    },
    {
      "to": "karura",
      "token": "PHA",
      "xcm": {
        "fee": {
          "token": "PHA",
          "amount": "51200000000"
        }
      },
      "from": "khala"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "4616667257"
        }
      },
      "from": "khala"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        }
      },
      "from": "khala"
    }
  ],
  [
    {
      "to": "acala",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "1222070"
        },
        "deliveryFee": {
          "token": "DOT",
          "amount": "397000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "polkadot"
    },
    {
      "to": "hydradx",
      "token": "DOT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "397000000"
        },
        "fee": {
          "token": "DOT",
          "amount": "21711791"
        },
        "weightLimit": "Unlimited"
      },
      "from": "polkadot"
    },
    {
      "to": "assetHubPolkadot",
      "token": "DOT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "397000000"
        },
        "fee": {
          "token": "DOT",
          "amount": "15800000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "polkadot"
    },
    {
      "to": "interlay",
      "token": "DOT",
      "xcm": {
        "deliveryFee": {
          "token": "DOT",
          "amount": "397000000"
        },
        "fee": {
          "token": "DOT",
          "amount": "25000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "polkadot"
    },
    {
      "to": "karura",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "44163610"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1323333009"
        },
        "weightLimit": "Unlimited"
      },
      "from": "kusama"
    },
    {
      "to": "basilisk",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "72711796"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1323333009"
        },
        "weightLimit": "Unlimited"
      },
      "from": "kusama"
    },
    {
      "to": "assetHubKusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "34368318"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1323333009"
        },
        "weightLimit": "Unlimited"
      },
      "from": "kusama"
    },
    {
      "to": "kintsugi",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "250000000"
        },
        "deliveryFee": {
          "token": "KSM",
          "amount": "1323333009"
        },
        "weightLimit": "Unlimited"
      },
      "from": "kusama"
    }
  ],
  [
    {
      "to": "hydradx",
      "token": "SUB",
      "xcm": {
        "fee": {
          "token": "SUB",
          "amount": "65000000"
        }
      },
      "from": "subsocial"
    },
    {
      "to": "moonbeam",
      "token": "SUB",
      "xcm": {
        "fee": {
          "token": "SUB",
          "amount": "65000000"
        }
      },
      "from": "subsocial"
    }
  ],
  [
    {
      "to": "acala",
      "token": "UNQ",
      "xcm": {
        "fee": {
          "token": "UNQ",
          "amount": "101030000000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "unique"
    },
    {
      "to": "karura",
      "token": "QTZ",
      "xcm": {
        "fee": {
          "token": "QTZ",
          "amount": "64000000000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "quartz"
    }
  ],
  [
    {
      "to": "hydradx",
      "token": "ZTG",
      "xcm": {
        "fee": {
          "token": "ZTG",
          "amount": "225000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "zeitgeist"
    }
  ]
]
  