
  // This file is generated by scripts/generate-bridge-document.ts
  export default [
  [
    {
      "to": "polkadot",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "469417452"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "GLMR",
      "xcm": {
        "fee": {
          "token": "GLMR",
          "amount": "8000000000000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "24963428577"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "2000000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "moonbeam",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "447889166"
        }
      },
      "from": "acala"
    },
    {
      "to": "parallel",
      "token": "PARA",
      "xcm": {
        "fee": {
          "token": "PARA",
          "amount": "9600000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "parallel",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "1920000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "parallel",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "2880000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "parallel",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "96000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "ASTR",
      "xcm": {
        "fee": {
          "token": "ASTR",
          "amount": "4006410300000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "1108000000"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "252800000"
        }
      },
      "from": "acala"
    },
    {
      "to": "astar",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "3692000"
        }
      },
      "from": "acala"
    },
    {
      "to": "interlay",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "21787589"
        }
      },
      "from": "acala"
    },
    {
      "to": "interlay",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "72"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "DAI",
      "xcm": {
        "fee": {
          "token": "DAI",
          "amount": "2926334210356268"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "491129243"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "WETH",
      "xcm": {
        "fee": {
          "token": "WETH",
          "amount": "956965470918"
        }
      },
      "from": "acala"
    },
    {
      "to": "hydradx",
      "token": "WBTC",
      "xcm": {
        "fee": {
          "token": "WBTC",
          "amount": "6"
        }
      },
      "from": "acala"
    },
    {
      "to": "unique",
      "token": "UNQ",
      "xcm": {
        "fee": {
          "token": "UNQ",
          "amount": ""
        }
      },
      "from": "acala"
    },
    {
      "to": "statemint",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "700000"
        }
      },
      "from": "acala"
    },
    {
      "to": "kusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "79999999"
        }
      },
      "from": "karura"
    },
    {
      "to": "statemine",
      "token": "RMRK",
      "xcm": {
        "fee": {
          "token": "RMRK",
          "amount": "100000"
        }
      },
      "from": "karura"
    },
    {
      "to": "statemine",
      "token": "ARIS",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "16000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "statemine",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "1183"
        }
      },
      "from": "karura"
    },
    {
      "to": "shiden",
      "token": "SDN",
      "xcm": {
        "fee": {
          "token": "SDN",
          "amount": "4006410300000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shiden",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "2080000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "BNC",
      "xcm": {
        "fee": {
          "token": "BNC",
          "amount": "5120000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "4800000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "25600000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "bifrost",
      "token": "VSKSM",
      "xcm": {
        "fee": {
          "token": "VSKSM",
          "amount": "64000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "altair",
      "token": "AIR",
      "xcm": {
        "fee": {
          "token": "AIR",
          "amount": "9269600000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "altair",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "51200000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shadow",
      "token": "CSM",
      "xcm": {
        "fee": {
          "token": "CSM",
          "amount": "4000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shadow",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "4000"
        }
      },
      "from": "karura"
    },
    {
      "to": "shadow",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "4000"
        }
      },
      "from": "karura"
    },
    {
      "to": "crab",
      "token": "CRAB",
      "xcm": {
        "fee": {
          "token": "CRAB",
          "amount": "4000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "integritee",
      "token": "TEER",
      "xcm": {
        "fee": {
          "token": "TEER",
          "amount": "4000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "kintsugi",
      "token": "KINT",
      "xcm": {
        "fee": {
          "token": "KINT",
          "amount": "170666666"
        }
      },
      "from": "karura"
    },
    {
      "to": "kintsugi",
      "token": "KBTC",
      "xcm": {
        "fee": {
          "token": "KBTC",
          "amount": "85"
        }
      },
      "from": "karura"
    },
    {
      "to": "kintsugi",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "186480000"
        }
      },
      "from": "karura"
    },
    {
      "to": "khala",
      "token": "PHA",
      "xcm": {
        "fee": {
          "token": "PHA",
          "amount": "64000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "khala",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "16000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "khala",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "8000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "kico",
      "token": "KICO",
      "xcm": {
        "fee": {
          "token": "KICO",
          "amount": "96000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "kico",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "160000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "kico",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "320000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "KMA",
      "xcm": {
        "fee": {
          "token": "KMA",
          "amount": "4000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "100000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "100000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "calamari",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "7692307692"
        }
      },
      "from": "karura"
    },
    {
      "to": "moonriver",
      "token": "MOVR",
      "xcm": {
        "fee": {
          "token": "MOVR",
          "amount": "80000000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "moonriver",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "9880000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "moonriver",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "16536000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "heiko",
      "token": "HKO",
      "xcm": {
        "fee": {
          "token": "HKO",
          "amount": "1440000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "heiko",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "2400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "heiko",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "19200000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "heiko",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "48000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "pichiu",
      "token": "PCHU",
      "xcm": {
        "fee": {
          "token": "PCHU",
          "amount": "400000000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "pichiu",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "pichiu",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "pichiu",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "TUR",
      "xcm": {
        "fee": {
          "token": "TUR",
          "amount": "1664000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "32000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "256000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "turing",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "BSX",
      "xcm": {
        "fee": {
          "token": "BSX",
          "amount": "22000000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "359882060"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "3150402683"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "DAI",
      "xcm": {
        "fee": {
          "token": "DAI",
          "amount": "4400000000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "USDCet",
      "xcm": {
        "fee": {
          "token": "USDCet",
          "amount": "4400"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "WETH",
      "xcm": {
        "fee": {
          "token": "WETH",
          "amount": "2926000000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "basilisk",
      "token": "WBTC",
      "xcm": {
        "fee": {
          "token": "WBTC",
          "amount": "22"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "LT",
      "xcm": {
        "fee": {
          "token": "LT",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "listen",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "6400000000"
        }
      },
      "from": "karura"
    },
    {
      "to": "quartz",
      "token": "QTZ",
      "xcm": {
        "fee": {
          "token": "QTZ",
          "amount": "0"
        }
      },
      "from": "karura"
    }
  ],
  [
    {
      "to": "acala",
      "token": "ASTR",
      "xcm": {
        "fee": {
          "token": "ASTR",
          "amount": "8082400000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "acala",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "8082400000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "acala",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "1815098681"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "acala",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "13400229"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "hydradx",
      "token": "ASTR",
      "xcm": {
        "fee": {
          "token": "ASTR",
          "amount": "44306118000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "astar"
    },
    {
      "to": "karura",
      "token": "SDN",
      "xcm": {
        "fee": {
          "token": "SDN",
          "amount": "801280000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "shiden"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "2120203588"
        },
        "weightLimit": "Unlimited"
      },
      "from": "shiden"
    }
  ],
  [
    {
      "to": "hydradx",
      "token": "BNC",
      "xcm": {
        "fee": {
          "token": "BNC",
          "amount": "14645000000"
        }
      },
      "from": "bifrost"
    },
    {
      "to": "hydradx",
      "token": "vDOT",
      "xcm": {
        "fee": {
          "token": "vDOT",
          "amount": "5550000"
        }
      },
      "from": "bifrost"
    }
  ],
  [
    {
      "to": "kusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "104571640"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "BSX",
      "xcm": {
        "fee": {
          "token": "BSX",
          "amount": "93240000000"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "5060238106"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "aUSD",
      "xcm": {
        "fee": {
          "token": "aUSD",
          "amount": "5060238106"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "90741527"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "DAI",
      "xcm": {
        "fee": {
          "token": "DAI",
          "amount": "808240000000000"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "USDCet",
      "xcm": {
        "fee": {
          "token": "USDCet",
          "amount": "808"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "WETH",
      "xcm": {
        "fee": {
          "token": "WETH",
          "amount": "449022222222"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "karura",
      "token": "WBTC",
      "xcm": {
        "fee": {
          "token": "WBTC",
          "amount": "2"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "statemine",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "1183"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "tinkernet",
      "token": "TNKR",
      "xcm": {
        "fee": {
          "token": "TNKR",
          "amount": "9270203240"
        }
      },
      "from": "basilisk"
    },
    {
      "to": "robonomics",
      "token": "XRT",
      "xcm": {
        "fee": {
          "token": "XRT",
          "amount": "4632"
        }
      },
      "from": "basilisk"
    }
  ],
  [
    {
      "to": "karura",
      "token": "TEER",
      "xcm": {
        "fee": {
          "token": "TEER",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "integritee"
    }
  ],
  [
    {
      "to": "acala",
      "token": "INTR",
      "xcm": {
        "fee": {
          "token": "INTR",
          "amount": "92696000"
        }
      },
      "from": "interlay"
    },
    {
      "to": "acala",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "9"
        }
      },
      "from": "interlay"
    },
    {
      "to": "hydradx",
      "token": "IBTC",
      "xcm": {
        "fee": {
          "token": "IBTC",
          "amount": "7"
        }
      },
      "from": "interlay"
    },
    {
      "to": "karura",
      "token": "KINT",
      "xcm": {
        "fee": {
          "token": "KINT",
          "amount": "170666666"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    },
    {
      "to": "karura",
      "token": "KBTC",
      "xcm": {
        "fee": {
          "token": "KBTC",
          "amount": "85"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "647055467"
        },
        "weightLimit": "5000000000"
      },
      "from": "kintsugi"
    }
  ],
  [
    {
      "to": "karura",
      "token": "KICO",
      "xcm": {
        "fee": {
          "token": "KICO",
          "amount": "6400000000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "kico"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "kico"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "10011896008"
        },
        "weightLimit": "5000000000"
      },
      "from": "kico"
    }
  ],
  [
    {
      "to": "karura",
      "token": "PCHU",
      "xcm": {
        "fee": {
          "token": "PCHU",
          "amount": "9324000000000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "pichiu"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "9324000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "pichiu"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "5060238106"
        },
        "weightLimit": "5000000000"
      },
      "from": "pichiu"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "700170039"
        },
        "weightLimit": "5000000000"
      },
      "from": "pichiu"
    }
  ],
  [
    {
      "to": "karura",
      "token": "LT",
      "xcm": {
        "fee": {
          "token": "LT",
          "amount": "93240000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "9324000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "5693632140"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "739331668"
        },
        "weightLimit": "5000000000"
      },
      "from": "listen"
    }
  ],
  [
    {
      "to": "karura",
      "token": "KMA",
      "xcm": {
        "fee": {
          "token": "KMA",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "6381112603"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "452334406"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    },
    {
      "to": "karura",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "54632622"
        },
        "weightLimit": "5000000000"
      },
      "from": "calamari"
    }
  ],
  [
    {
      "to": "karura",
      "token": "TUR",
      "xcm": {
        "fee": {
          "token": "TUR",
          "amount": "2560000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "2626579278"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "480597195"
        },
        "weightLimit": "5000000000"
      },
      "from": "turing"
    }
  ],
  [
    {
      "to": "acala",
      "token": "PARA",
      "xcm": {
        "fee": {
          "token": "PARA",
          "amount": "6400000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "parallel"
    },
    {
      "to": "acala",
      "token": "ACA",
      "xcm": {
        "fee": {
          "token": "ACA",
          "amount": "6400000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "parallel"
    },
    {
      "to": "acala",
      "token": "AUSD",
      "xcm": {
        "fee": {
          "token": "AUSD",
          "amount": "3721109059"
        },
        "weightLimit": "Unlimited"
      },
      "from": "parallel"
    },
    {
      "to": "acala",
      "token": "LDOT",
      "xcm": {
        "fee": {
          "token": "LDOT",
          "amount": "24037893"
        },
        "weightLimit": "Unlimited"
      },
      "from": "parallel"
    },
    {
      "to": "karura",
      "token": "HKO",
      "xcm": {
        "fee": {
          "token": "HKO",
          "amount": "6400000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "heiko"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "heiko"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "8305746640"
        },
        "weightLimit": "Unlimited"
      },
      "from": "heiko"
    },
    {
      "to": "karura",
      "token": "LKSM",
      "xcm": {
        "fee": {
          "token": "LKSM",
          "amount": "589618748"
        },
        "weightLimit": "Unlimited"
      },
      "from": "heiko"
    }
  ],
  [
    {
      "to": "karura",
      "token": "PHA",
      "xcm": {
        "fee": {
          "token": "PHA",
          "amount": "51200000000"
        }
      },
      "from": "khala"
    },
    {
      "to": "karura",
      "token": "KUSD",
      "xcm": {
        "fee": {
          "token": "KUSD",
          "amount": "4616667257"
        }
      },
      "from": "khala"
    },
    {
      "to": "karura",
      "token": "KAR",
      "xcm": {
        "fee": {
          "token": "KAR",
          "amount": "6400000000"
        }
      },
      "from": "khala"
    }
  ],
  [
    {
      "to": "acala",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "3549633"
        },
        "weightLimit": "Unlimited"
      },
      "from": "polkadot"
    },
    {
      "to": "hydradx",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "21711791"
        },
        "weightLimit": "Unlimited"
      },
      "from": "polkadot"
    },
    {
      "to": "statemint",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "15800000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "polkadot"
    },
    {
      "to": "karura",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "44163610"
        },
        "weightLimit": "Unlimited"
      },
      "from": "kusama"
    },
    {
      "to": "basilisk",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "72711796"
        },
        "weightLimit": "Unlimited"
      },
      "from": "kusama"
    },
    {
      "to": "statemine",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "34368318"
        },
        "weightLimit": "Unlimited"
      },
      "from": "kusama"
    }
  ],
  [
    {
      "to": "polkadot",
      "token": "DOT",
      "xcm": {
        "fee": {
          "token": "DOT",
          "amount": "421500000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemint"
    },
    {
      "to": "hydradx",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "2200"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemint"
    },
    {
      "to": "hydradx",
      "token": "USDC",
      "xcm": {
        "fee": {
          "token": "USDC",
          "amount": "2200"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemint"
    },
    {
      "to": "acala",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "808"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemint"
    },
    {
      "to": "kusama",
      "token": "KSM",
      "xcm": {
        "fee": {
          "token": "KSM",
          "amount": "90049287"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemine"
    },
    {
      "to": "karura",
      "token": "RMRK",
      "xcm": {
        "fee": {
          "token": "RMRK",
          "amount": "9918117"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemine"
    },
    {
      "to": "karura",
      "token": "ARIS",
      "xcm": {
        "fee": {
          "token": "ARIS",
          "amount": "6400000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemine"
    },
    {
      "to": "karura",
      "token": "USDT",
      "xcm": {
        "fee": {
          "token": "USDT",
          "amount": "808"
        },
        "weightLimit": "Unlimited"
      },
      "from": "statemine"
    }
  ],
  [
    {
      "to": "acala",
      "token": "UNQ",
      "xcm": {
        "fee": {
          "token": "UNQ",
          "amount": "101030000000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "unique"
    },
    {
      "to": "karura",
      "token": "QTZ",
      "xcm": {
        "fee": {
          "token": "QTZ",
          "amount": "64000000000000000"
        },
        "weightLimit": "Unlimited"
      },
      "from": "quartz"
    }
  ],
  [
    {
      "to": "hydradx",
      "token": "ZTG",
      "xcm": {
        "fee": {
          "token": "ZTG",
          "amount": "225000000"
        },
        "weightLimit": "5000000000"
      },
      "from": "zeitgeist"
    }
  ]
]
  